version: '3.7'

services:
  chatdb:
    image: postgres:15-bookworm
    container_name: chatdb
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
        interval: 20s
        timeout: 5s
        retries: 5
    restart: always

  redis:
    image: redis:7.2.4-bookworm
    env_file:
      - .env
    expose:
      - 6379
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  django:
    build:
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      chatdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    container_name: djangochat
    volumes:
      - ./chat/debug.log:/home/chat/chat/debug.log
    restart: always

  chatnginx:
    build: nginx
    ports:
      - "80:80"
    container_name: chatnginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./chat/static:/static:ro
    depends_on:
      - django

volumes:
  postgres_data:

networks:
  mainnetwork:
    external: true
