version: '3.7'

services:
  usersdb:
    image: postgres:16.2-bookworm
    container_name: usersdb
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
        interval: 20s
        timeout: 5s
        retries: 5
    restart: always
  usersapp:
    build:
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      - usersdb
    env_file:
      - .env
    container_name: usersapp
    volumes:
      - ./users/debug.log:/home/app/users/debug.log
      - ./users:/home/app/users
    restart: always
  usersapp1:
    build:
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      - usersdb
    env_file:
      - .env
    container_name: usersapp1
    volumes:
      - ./users/debug.log:/home/app/users/debug.log
      - ./users:/home/app/users
    restart: always
  usersapp2:
    build:
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      - usersdb
    env_file:
      - .env
    container_name: usersapp2
    volumes:
      - ./users/debug.log:/home/app/users/debug.log
      - ./users:/home/app/users
    restart: always
  usersapp3:
    build:
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      - usersdb
    env_file:
      - .env
    container_name: usersapp3
    volumes:
      - ./users/debug.log:/home/app/users/debug.log
      - ./users:/home/app/users
    restart: always
  usersredis:
    image: redis:7.2.4-bookworm
    env_file:
      - .env
    expose:
      - 6379
    container_name: usersredis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
  userscelery:
    build:
      dockerfile: Dockerfile.celery
    restart: always
    command: celery -A common beat -l info -f /home/app/users/celery.log
    container_name: userscelery
    volumes:
      - ./users/celery.log:/home/app/users/celery.log
    env_file:
      - .env
    depends_on:
      - usersdb
      - usersredis
  usersnginx:
    build: nginx
    expose:
      - 80
    depends_on:
      - usersapp
    container_name: usersnginx
    volumes:
      - ./users/static/:/users/static
      - ./users/:/home/app/users
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:

networks:
  mainnetwork:
    external: true
