version: '3.7'

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - mainnetwork

networks:
  mainnetwork:
    name: mainnetwork
    external: true
