version: '3.7'

services:
  nginx:
    build: nginx
    ports:
      - "443:443"
      - "80:80"
    container_name: nginx
    network_mode: bridge
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/jackdrop.online/fullchain.pem:/etc/letsencrypt/live/jackdrop.online/fullchain.pem
      - /etc/letsencrypt/live/jackdrop.online/privkey.pem:/etc/letsencrypt/live/jackdrop.online/privkey.pem

networks:
  mainnetwork:
    external: true
