version: '3.7'

services:
  gamesdb:
    image: postgres:16.2-bookworm
    container_name: gamesdb
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
        interval: 20s
        timeout: 5s
        retries: 5
    restart: always
  gamesapp:
    build:
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      - gamesdb
    env_file:
      - .env
    volumes:
      - .:/home/app/
    container_name: gamesapp
    restart: always
  gamesnginx:
    build: nginx
    expose:
      - 80
    depends_on:
      - gamesapp
    container_name: gamesnginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./games/static:/games/static/
  gamesredis:
    image: redis:7.2.4-bookworm
    env_file:
      - .env
    expose:
      - 6379
    container_name: gamesredis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
  gamescelery:
    build:
      dockerfile: Dockerfile.celery
    restart: always
    command: celery -A common beat -l info -f /home/app/games/celery.log
    container_name: gamescelery
    volumes:
      - ./games/:/home/app/games/
    env_file:
      - .env
    depends_on:
      - gamesdb
      - gamesredis
      - gamesapp

volumes:
  postgres_data:

networks:
  mainnetwork:
    external: true
