version: '3.7'

services:
  gamesdb:
    image: postgres:16.2-bookworm
    container_name: gamesdb
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
        interval: 20s
        timeout: 5s
        retries: 5
    restart: always
  gamesapp:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - gamesdb
    env_file:
      - .env
    container_name: gamesapp
    restart: always


volumes:
  postgres_data:

networks:
  mainnetwork:
    external: true
