version: '3.7'

services:
  productsdb:
    image: postgres:16.2-bookworm
    container_name: productsdb
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
        interval: 20s
        timeout: 5s
        retries: 5
    restart: always
  productsredis:
    image: redis:7.2.4-bookworm
    env_file:
      - .env
    expose:
      - 6379
    container_name: productsredis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
  productsapp:
    build:
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      - productsdb
      - productsredis
    env_file:
      - .env
    container_name: productsapp
    volumes:
#      - ./products/debug.log:/home/app/products/debug.log
      - ./products/:/home/app/products/
    restart: always
  productscelery:
    build:
      dockerfile: Dockerfile.celery
    restart: always
    command: celery -A common beat -l info -f /home/app/products/celery.log
    container_name: productscelery
    volumes:
      - ./products/:/home/app/products/
    env_file:
      - .env
    depends_on:
      - productsdb
      - productsredis
      - productsapp
  productsnginx:
    build: nginx
    expose:
      - 80
    depends_on:
      - productscelery
    container_name: productsnginx
    volumes:
      - ./products/static/:/products/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:

networks:
  mainnetwork:
    external: true