version: '3.7'

services:
  productsdb:
    image: postgres:16.2-bookworm
    container_name: productsdb
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
        interval: 20s
        timeout: 5s
        retries: 5
    restart: always
  productsapp:
    build:
      dockerfile: Dockerfile
    expose:
      - 8000
    depends_on:
      - productsdb
    env_file:
      - .env
    container_name: productsapp
    volumes:
      - ./products/debug.log:/home/app/products/debug.log
    restart: always
  productsnginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - productsapp
    container_name: productsnginx
    volumes:
      - ./products/static/:/products/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:

networks:
  mainnetwork:
    external: true